### ISSUE TITLE
Types in interfaces 

### ISSUE THREAD

**Issue by dvmhmdsd** [moatazalaa14/Todo-App-Typescript#3]
https://github.com/moatazalaa14/Todo-App-Typescript/blob/26d277feab9873c397feb46f4adec50ed6525f20/src/interfaces/todo.ts#L6

What's the purposes of these types inside the interface file and what dows it do ?

**Comment by moatazalaa14** [comment]
> type aliases can act sort of like interfaces


so that I try to use type aliases and interfaces only that no reason for that 😂😂
For the question "what does it do":
if you ask about  line'6 , just it is a function take one argument which datatype is Todo 
`export interface Todo{
    name:string;
    isComplete:boolean;
  }`
 and function don't return any thing 😂😂
but I think you ask about why I use "type" particularly .
 no clear differences between them so I just try to use it 😂
